name: Black Duck scan

on:
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node dependencies
        working-directory: ./web
        run: npm install

      - name: Run Black Duck scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackducksca_url: https://apus-blackduck.volvocars.biz
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          detect_search_depth: 10
          detect_args: >-
            --detect.blackduck.signature.scanner.copyright.search=true
            --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
            --detect.timeout=3000
            --detect.accuracy.required=NONE
            --detect.tools=SIGNATURE_SCAN,DETECTOR
            --detect.npm.include.dev.dependencies=true
            --detect.bazel.enabled=true
            --detect.project.version.name=main

      - name: Copy notice report
        run: |
          mkdir -p reports
          cp /github/workspace/blackduck/reports/notice.txt reports/NOTICE.generated.txt

      - name: Upload NOTICE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: notice-report
          path: reports/NOTICE.generated.txt
