name: Black Duck full scan

on:
  workflow_dispatch:

jobs:
  blackduck-combined:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        working-directory: web
        run: npm install

      - name: Set up JDK for Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Black Duck scan for full repo (Java + Node)
        uses: blackduck-inc/black-duck-security-scan@6ee400ee2502a366bdff13cddae76bbde804fd20 # v2.1.1

        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackducksca_url: https://apus-blackduck.volvocars.biz
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          detect_search_depth: 10
          detect_args: >-
            --detect.tools=DETECTOR
            --detect.maven.build.command=dependency:resolve
            --detect.npm.include.dev.dependencies=true
            --detect.detector.search.continue=true
            --detect.bazel.enabled=true
            --detect.accuracy.required=NONE
            --detect.timeout=3000
            --detect.code.location.delete=true
            --detect.project.version.name=v0.1.0
