name: Black Duck scan

on:
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (latest LTS) with nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          source ~/.nvm/nvm.sh
          nvm install --lts
          node -v
          npm -v


      - name: Run Black Duck scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        with:
          blackducksca_url: https://apus-blackduck.volvocars.biz
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          detect_search_depth: 10
          detect_args: >-
            --detect.blackduck.signature.scanner.copyright.search=true
            --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
            --detect.timeout=3000
            --detect.accuracy.required=NONE
            --detect.tools=SIGNATURE_SCAN,DETECTOR
            --detect.npm.include.dev.dependencies=true
            --detect.bazel.enabled=true
            --detect.project.version.name=main

