name: Black Duck scan

on:
  workflow_dispatch:

jobs:
  blackduck-scan:
    runs-on: ubuntu-latest
    env:
      DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
      DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run Black Duck SCA scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        with:
          blackducksca_url: https://apus-blackduck.volvocars.biz
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          detect_search_depth: 3
          detect_args: >
            --detect.report.notice=true
            --detect.report.pdf=true
            --detect.accuracy.required=HIGH
            --detect.timeout=3000
            --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
            --detect.blackduck.signature.scanner.copyright.search=true