name: Black Duck Java scan

on:
  workflow_dispatch:

jobs:
  blackduck-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK for Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify pom.xml exists
        run: ls -l pom.xml

      - name: Resolve Maven dependencies and list them
        run: |
          mvn dependency:resolve
          mvn dependency:list -DincludeScope=compile -DoutputFile=dependencies.txt
          cat dependencies.txt

      - name: Run Black Duck scan for Java
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}-java
        with:
          blackducksca_url: https://apus-blackduck.volvocars.biz
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          detect_search_depth: 10
          detect_args: >-
            --detect.tools=DETECTOR
            --detect.maven.build.command=dependency:resolve
            --detect.project.version.name=java-scan
            --detect.timeout=3000
            --detect.force.success=true
            --logging.level.com.synopsys.integration=DEBUG
